version: '3.8'
services:
  frontend:
    image: iine_frontend
    ports:
      - '4000:4000'

  backend:
    image: iine_backend
    environment:
      NODE_ENV: ${NODE_ENV}
      IINE_DATABASE: ${MONGO_INITDB_DATABASE}
      IINE_DB_UERNAME: ${MONGO_IINE_UERNAME}
      IINE_DB_PASSWORD: ${MONGO_IINE_PASSWORD}
      BUCKET_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      BUCKET_SECRET_KEY: ${MINIO_SECRET_KEY}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - '3003:3003'
    volumes:
      - ./volume/iine-backend/logs:/logs
  
  mongo:
    image: 'mongo:5.0'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_IINE_UERNAME: ${MONGO_IINE_UERNAME}
      MONGO_IINE_PASSWORD: ${MONGO_IINE_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - ./volume/mongo/db:/data/db
      - ./volume/mongo/configdb:/data/configdb

  fraweb:
    build: ./fraweb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - sockets:/var/tmp/sockets
      - ./volume/fraweb/log:/var/log/nginx
volumes:
  sockets:
